import { IBM_Plex_Mono, Hanken_Grotesk, Inter } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import { twMerge } from "tailwind-merge";
import Header from "@/components/common/Header";
import { cn } from "@/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const ibmPlexMono = IBM_Plex_Mono({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});
const hankenGrotesk = Hanken_Grotesk({ weight: ["900"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={cn("font-sans", inter.variable)}>
      <body
        className={twMerge(
          "bg-background text-zinc-100 antialiased",
          ibmPlexMono.className,
        )}
      >
        <Header className={hankenGrotesk.className} />
        {children}
      </body>
    </html>
  );
}
